### ISSUE TITLE
Check list before re-submission

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/Evolutionary-game-theoretic-Model-of-Rhino-poaching#71]
Hi all:

# @drvinceknight

- [x] Read the marked-up diff file (this depends on #70)
- [x] Read the paper (verify new conclusions, new notation etc)
- [x] Read the the list of original comments and check the response to make sure nothing has been omitted and everything is correct (this depends on #69).

# @Nikoleta-v3 

- [x] Read the marked-up diff file (this depends on #70)
- [x] Read the paper (verify new conclusions, new notation etc)
- [x] Read the list of original comments and check the response to make sure nothing has been omitted and everything is correct (this depends on #69).

# @TamsinELee 

- [x] Read the marked-up diff file (this depends on #70)
- [x] Read the paper (verify new conclusions, new notation etc)
- [x] Read the list of original comments and check the response to make sure nothing has been omitted and everything is correct (this depends on #69).
